# ukratko nije mi se dalo pisat cijene za svaki grad svaki prijevoz napravia san ovo


import random


data = [
    { "id": "Bangkok", "kontinent": "Azija", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Beograd", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Berlin", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Brasília", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Buenos Aires", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Ciudad de Panamá", "kontinent": "Srednja Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Georgetown", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Kairo", "kontinent": "Afrika", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Kuala Lumpur", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Lima", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Mbabane", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "New Delhi", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Pariz", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Peking", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Prag", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Quito", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Santiago", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "São Tomé", "kontinent": "Afrika", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Sarajevo", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Tokio", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Valletta", "kontinent": "Europa", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Zagreb", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Canberra", "kontinent": "Australija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Oslo", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Nairobi", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Addis Abeba", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Manila", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Makao", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Niamey", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Kampala", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Jakarta", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Kingston", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Reykjavik", "kontinent": "Europa", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Asmara", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Oranjestad", "kontinent": "Karibi", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Pyongyang", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Lomé", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Lilongwe", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Seoul", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "The Valley", "kontinent": "Karibi", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Maputo", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Wellington", "kontinent": "Australija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Port Louis", "kontinent": "Afrika", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Lisabon", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Gaborone", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "West Island", "kontinent": "Okeanija", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Bissau", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Bandar Seri Begawan", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Rim", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Podgorica", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Varšava", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Papeete", "kontinent": "Okeanija", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Yaren", "kontinent": "Okeanija", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Singapur", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Riga", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Praia", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Ouagadougou", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Antananarivo", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Kabul", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Saint-Denis", "kontinent": "Okeanija", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Asunción", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Sofia", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Bruxelles", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Luanda", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Kopenhagen", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Dodoma", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "San José", "kontinent": "Srednja Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Bishkek", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Victoria", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Brazzaville", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Tehran", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Gibraltar", "kontinent": "Europa", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Andorra la Vella", "kontinent": "Europa", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Pretoria", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Helsinki", "kontinent": "Europa", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Maseru", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Kigali", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Nouakchott", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Masqat", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Honiara", "kontinent": "Okeanija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Bukurešt", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Abu Dhabi", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Ottawa", "kontinent": "Sjeverna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Cardiff", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Città del Vaticano", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Paramaribo", "kontinent": "Južna Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Basseterre", "kontinent": "Srednja Amerika", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Skopje", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Thimphu", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Ankara", "kontinent": "Europa", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Mamoudzou", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Dušanbe", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Ljubljana", "kontinent": "Europa", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Tegucigalpa", "kontinent": "Srednja Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Yamoussoukro", "kontinent": "Afrika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Belmopan", "kontinent": "Srednja Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Port-au-Prince", "kontinent": "Srednja Amerika", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Erevan", "kontinent": "Azija", "prijevoz": ["AV", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Flying Fish Cove", "kontinent": "Okeanija", "prijevoz": ["AV", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Adis Abeba", "kontinent": "Afrika", "prijevoz": ["AV", "BUS", "VL"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Asmera", "kontinent": "Afrika", "prijevoz": ["AV", "VL", "BUS"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Pjongjang", "kontinent": "Azija", "prijevoz": ["AV", "BUS", "VL"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Vis", "kontinent": "Europa", "prijevoz": ["BROD"], "cijena": [{ "id": "BROD", "n": 100 }] },
    { "id": "Lisbon", "kontinent": "Europa", "prijevoz": ["AV", "BUS", "VLAK", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Warszawa", "kontinent": "Europa", "prijevoz": ["AV", "BUS", "VLAK"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },
    { "id": "Copenhagen", "kontinent": "Europa", "prijevoz": ["AV", "BUS", "VLAK", "BROD"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }, { "id": "BROD", "n": 100 }] },
    { "id": "Ankaru", "kontinent": "Azija", "prijevoz": ["AV", "BUS", "VLAK"], "cijena": [{ "id": "AV", "n": 100 }, { "id": "VL", "n": 100 }, { "id": "BUS", "n": 100 }] },

]

def randomize_cijena(input_list):
    for entry in input_list:
        for cijena_item in entry["cijena"]:
            cijena_item["n"] = random.randint(100, 300)
    return input_list


randomized_data = randomize_cijena(data)


for entry in randomized_data:
    print(entry, ",")